import 'package:merrymakin/commons/models/country_currency.dart';
import 'package:merrymakin/commons/models/event.dart';
import 'package:merrymakin/commons/models/user.dart';

class Seed {
  static final List<User> sampleUsers = [
    User(
      id: '1',
      email: 'john.doe@example.com',
      givenName: 'John',
      familyName: 'Doe',
      username: 'johndoe',
      photoUrl: 'https://picsum.photos/200?random=1',
      firstRegistered: DateTime.now().subtract(const Duration(days: 100)),
      timeStampWhenAuthorized: DateTime.now(),
    ),
    User(
      id: '2',
      email: 'jane.smith@example.com',
      givenName: 'Jane',
      familyName: 'Smith',
      username: 'janesmith',
      photoUrl: 'https://picsum.photos/200?random=2',
      firstRegistered: DateTime.now().subtract(const Duration(days: 90)),
      timeStampWhenAuthorized: DateTime.now(),
    ),
    User(
      id: '3',
      email: 'mike.wilson@example.com',
      givenName: 'Mike',
      familyName: 'Wilson',
      username: 'mikewilson',
      photoUrl: 'https://picsum.photos/200?random=3',
      firstRegistered: DateTime.now().subtract(const Duration(days: 80)),
      timeStampWhenAuthorized: DateTime.now(),
    ),
    User(
      id: '4',
      email: 'sarah.johnson@example.com',
      givenName: 'Sarah',
      familyName: 'Johnson',
      username: 'sarahj',
      photoUrl: 'https://picsum.photos/200?random=4',
      firstRegistered: DateTime.now().subtract(const Duration(days: 70)),
      timeStampWhenAuthorized: DateTime.now(),
    ),
    User(
      id: '5',
      email: 'david.brown@example.com',
      givenName: 'David',
      familyName: 'Brown',
      username: 'davidb',
      photoUrl: 'https://picsum.photos/200?random=5',
      firstRegistered: DateTime.now().subtract(const Duration(days: 60)),
      timeStampWhenAuthorized: DateTime.now(),
    ),
  ];

  static final List<Event> sampleEvents = [
    Event(
      id: '1',
      name: 'Summer Music Festival',
      imageUrl: 'https://picsum.photos/800/600?random=1',
      startDateTime: DateTime.now().add(const Duration(days: 2)),
      endDateTime: DateTime.now().add(const Duration(days: 2, hours: 4)),
      description: 'Join us for an amazing summer music festival!',
      location: 'Central Park, New York',
      spots: 100,
      costPerSpot: 49.99,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[0], sampleUsers[1]],
      // eventToAttendees: [sampleUsers[2], sampleUsers[3], sampleUsers[4]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Event(
      id: '2',
      name: 'Tech Conference 2024',
      imageUrl: 'https://picsum.photos/800/600?random=2',
      startDateTime: DateTime.now().add(const Duration(days: 5)),
      endDateTime: DateTime.now().add(const Duration(days: 5, hours: 8)),
      description: 'The biggest tech conference of the year',
      location: 'Convention Center, San Francisco',
      spots: 500,
      costPerSpot: 299.99,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[1], sampleUsers[2]],
      // guests: [sampleUsers[0], sampleUsers[4]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Event(
      id: '3',
      name: 'Cooking Workshop',
      imageUrl: 'https://picsum.photos/800/600?random=3',
      startDateTime: DateTime.now().add(const Duration(days: 3)),
      endDateTime: DateTime.now().add(const Duration(days: 3, hours: 3)),
      description: 'Learn to cook authentic Italian cuisine',
      location: 'Culinary Institute, Chicago',
      spots: 20,
      costPerSpot: 75.00,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[2]],
      // guests: [sampleUsers[0], sampleUsers[1], sampleUsers[3]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Event(
      id: '4',
      name: 'Yoga Retreat',
      imageUrl: 'https://picsum.photos/800/600?random=4',
      startDateTime: DateTime.now().add(const Duration(days: 10)),
      endDateTime: DateTime.now().add(const Duration(days: 12)),
      description: 'Weekend wellness retreat with yoga and meditation',
      location: 'Mountain View Resort, Colorado',
      spots: 30,
      costPerSpot: 399.99,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[3], sampleUsers[4]],
      // guests: [sampleUsers[0], sampleUsers[1]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Event(
      id: '5',
      name: 'Photography Workshop',
      imageUrl: 'https://picsum.photos/800/600?random=5',
      startDateTime: DateTime.now().add(const Duration(days: 4)),
      endDateTime: DateTime.now().add(const Duration(days: 4, hours: 6)),
      description: 'Master the art of landscape photography',
      location: 'Yosemite National Park',
      spots: 15,
      costPerSpot: 199.99,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[4]],
      // guests: [sampleUsers[1], sampleUsers[2]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Event(
      id: '6',
      name: 'Startup Networking',
      imageUrl: 'https://picsum.photos/800/600?random=6',
      startDateTime: DateTime.now().add(const Duration(days: 1)),
      endDateTime: DateTime.now().add(const Duration(days: 1, hours: 4)),
      description: 'Connect with fellow entrepreneurs',
      location: 'WeWork Downtown, Seattle',
      spots: 50,
      costPerSpot: 0,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[0], sampleUsers[3]],
      // guests: [sampleUsers[1], sampleUsers[2], sampleUsers[4]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Event(
      id: '7',
      name: 'Art Exhibition',
      imageUrl: 'https://picsum.photos/800/600?random=7',
      startDateTime: DateTime.now().add(const Duration(days: 15)),
      endDateTime: DateTime.now().add(const Duration(days: 20)),
      description: 'Contemporary art showcase featuring local artists',
      location: 'Modern Art Gallery, Miami',
      spots: 200,
      costPerSpot: 25.00,
      countryCurrency: CountryCurrency.UnitedStatesDollarUnitedStates,
      hosts: [sampleUsers[2], sampleUsers[4]],
      // guests: [sampleUsers[0], sampleUsers[1], sampleUsers[3]],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];
  static final User me = sampleUsers[0];
} 